/* Portfolio QA — idioma, tema e efeitos da página principal. */
(function () {
  'use strict';

  var GITHUB_URL = 'https://github.com/chriscsantosqa';
  var PROJECT_URLS = {
    playwright: './projetos/playwright-api/',
    dashboard: './projetos/qa-dashboard/',
    llm: './projetos/llm-rag/',
    apiCollections: './projetos/api-collections/'
  };
  var ARROW_SVG = '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M7 17 17 7M9 7h8v8"></path></svg>';

  var I18N = {
    pt: {
      navExp:'Experiência',navSkills:'Stack',navProj:'Projetos',navForm:'Formação',navContact:'Contato',heroHello:'$ olá, eu sou',
      heroLead:'Analista de QA com atuação em testes funcionais, exploratórios, automação, APIs e IA aplicada à qualidade. Transformo requisitos em confiança de entrega — da condição de teste ao report do incidente.',
      heroLoc:'Araçatuba — SP, Brasil',ctaContact:'Entrar em contato',termStatus:'status: qualidade em dia',skillsKicker:'stack técnica',skillsTitle:'Ferramentas & competências',
      expKicker:'trajetória',expTitle:'Experiência',expLead:'Da construção de condições de teste à automação, com foco em entregar produtos de qualidade junto ao time.',
      valAutoT:'Automação de ponta a ponta',valAutoD:'Playwright, Cypress e C# cobrindo UI e APIs, com resultados visíveis em relatórios Allure.',
      valAiT:'IA aplicada à qualidade',valAiD:'LLMs com RAG, agentes e MCP integrados ao ciclo de QA e aos processos do negócio.',
      valMetT:'Qualidade guiada por métricas',valMetD:'Dashboards de métricas e ciclo de vida extraídos do Azure DevOps via WIQL, com análise por IA.',
      valProcT:'Processo com maturidade',valProcD:'TMMi como referência internacional de qualidade, com Scrum e Kanban no dia a dia do time.',
      projKicker:'cases',projTitle:'Projetos & cases de teste',projLead:'Projetos reais construídos ao longo da trajetória — automação, dados e IA aplicados à qualidade de software.',projCta:'Ver no GitHub',
      formKicker:'formação',formTitle:'Formação acadêmica',formLead:'Graduação em tecnologia, pós em automação de testes e formação contínua na área de qualidade de software.',
      certTitle:'Cursos & certificações',langTitle:'Idiomas',contactTitle:'Vamos conversar sobre qualidade?',contactLead:'Aberto a oportunidades e boas conversas sobre testes, automação e qualidade de software. Me chame e marcamos um papo. 👋',footerCopy:'Alguns direitos reservados.',
      roles:['QA Analyst','Automação de Testes','Testes de API','IA aplicada à Qualidade','Testes Exploratórios'],
      experience:[
        {year:'2023 —',company:'Empresa de tecnologia e saúde',role:'QA Analyst',text:'À frente da implantação do processo de QA, estruturando a qualidade em todo o ciclo de vida do desenvolvimento — do refinamento à entrega — com automação, métricas e IA aplicadas ao dia a dia do time.',highlights:[
          'Implantação da estrutura de automação de checagens de API com Playwright e C#, com monitoramento e visibilidade dos resultados via relatórios Allure.',
          'Implantação do framework TMMi junto ao time, estruturando o processo de qualidade em aderência a referências internacionais.',
          'Planejamento e execução de condições de teste no Azure DevOps, com conhecimento avançado da plataforma e de suas integrações.',
          'Criação de dashboard desktop com Electron, React, JavaScript e Tailwind integrado ao Azure DevOps via WIQL para métricas, ciclo de vida, artefatos, estimativas e análises.',
          'Desenvolvimento de LLM local com Ollama, FastAPI e RAG, estruturando uma base de conhecimento para consultas e análises.',
          'Criação de agentes de IA com ferramentas personalizadas para análise de artefatos e consulta de endpoints de negócio.',
          'Apoio à gestão no acompanhamento e desenvolvimento de novos colaboradores do time.'
        ],tags:['Playwright','C#','Allure','Azure DevOps','TMMi','Postman','REST','GraphQL','HotChocolate','LLMs / RAG','MCP','Scrum','Kanban']},
        {year:'2023',company:'Lacrei Saúde',role:'QA Analyst · Voluntário',text:'Qualidade da plataforma de atendimento clínico para a comunidade LGBTQIAPN+ — condições de teste, cenários em Gherkin, automação com Cypress e report de incidentes.',tags:['Cypress','Gherkin','Postman','Swagger','Kanban','Figma','Notion']},
        {year:'2023',company:'Crowdtest',role:'Tester · Freelance',text:'Testes exploratórios e funcionais em projetos de diversos segmentos, em plataforma de crowdtesting.',tags:['Testes Exploratórios','Testes Funcionais','Web']},
        {year:'2023',company:'uTest',role:'Tester · Freelance',text:'Testes exploratórios, funcionais, web e mobile em projetos internacionais, incluindo produtos com I.A.',tags:['A.I','Mobile','Web','Testes Exploratórios']},
        {year:'2014 – 21',company:'Designer Gráfico',role:'Freelance',text:'Logotipos, banners, landing pages e social media — base sólida de UX/UI que hoje apoia o olhar crítico de QA sobre interfaces.',tags:['Illustrator','Photoshop','HTML','CSS','UX/UI','Figma']}
      ],
      skillGroups:[
        {name:'Testes',tags:['Exploratórios','Funcionais','Web','Mobile','API']},{name:'Automação',tags:['Playwright','Cypress','C#','JavaScript','Allure','Robot Framework','Gherkin / BDD']},
        {name:'API & Dados',tags:['Postman','REST','GraphQL','HotChocolate','Swagger','SQL Server']},{name:'IA aplicada à QA',tags:['LLMs / RAG','Ollama','Agentes de IA','MCP','FastAPI','OpenWebUI']},
        {name:'Processo & Ferramentas',tags:['Azure DevOps','WIQL','TMMi','Scrum','Kanban','Notion','Figma']}
      ],
      projects:[
        {kicker:'Automação de API',title:'Framework Playwright + C#',body:'Estrutura de automação de checagens de API construída do zero com Playwright e C#, com monitoramento e visão dos resultados via relatórios Allure.',tags:['Playwright','C#','Allure'],url:PROJECT_URLS.playwright,cta:'Explorar projeto'},
        {kicker:'Qualidade & Dados',title:'Dashboard de métricas de QA',body:'App desktop em Electron + React integrado ao Azure DevOps via WIQL: métricas de qualidade, ciclo de vida, riscos e apoio à tomada de decisão.',tags:['Electron','React','WIQL','MCP'],url:PROJECT_URLS.dashboard,cta:'Explorar projeto'},
        {kicker:'IA aplicada',title:'LLM corporativa com RAG',body:'LLM local com Ollama e FastAPI sobre base de conhecimento RAG em Markdown, com consultas especializadas e aprovação humana.',tags:['Ollama','RAG','FastAPI','Agentes'],url:PROJECT_URLS.llm,cta:'Explorar projeto'},
        {kicker:'Automação E2E',title:'Suíte Cypress — fluxos críticos',body:'Cenários end-to-end escritos em Gherkin e automatizados com Cypress, cobrindo os fluxos críticos da plataforma de atendimento.',tags:['Cypress','Gherkin','BDD']},
        {kicker:'Testes de API',title:'Coleções REST & GraphQL',body:'Coleções Postman para validação de contratos, status, segurança, persistência e regras de negócio em serviços REST e GraphQL.',tags:['Postman','GraphQL','Swagger'],url:PROJECT_URLS.apiCollections,cta:'Explorar projeto'},
        {kicker:'Documentação de QA',title:'Artefatos & rastreabilidade',body:'Planos e condições de teste, report e tracking de incidentes no Azure DevOps — rastreabilidade do requisito ao defeito.',tags:['Azure DevOps','SQL Server']}
      ],
      degrees:[{type:'Tecnólogo',course:'Análise e Desenvolvimento de Sistemas',school:'Uninter'},{type:'Pós-graduação · Cursando',course:'PGATS — Automação de Testes de Software',school:'Faculdade VINCIT'}],
      courses:[{name:'Mentoria em Testes de Software',hours:'90h+'},{name:'Programa de Testes e Qualidade de Software',hours:'85h+'},{name:'test.class — Escola de Testes de Software',hours:'30h+'},{name:'DTAR — Descomplicando Testes de API Rest',hours:'24h+'},{name:'HTML e CSS para Iniciantes',hours:'23h'},{name:'UX Design & UI Design',hours:'17h'},{name:'Automação de Testes com Robot Framework',hours:'7h'},{name:'Testes automatizados com Cypress — Básico',hours:'4,5h'},{name:'Testes automatizados com Cypress — Intermediário',hours:'3,5h'},{name:'Testes automatizados com Cypress — Avançado',hours:'2,5h'}],
      languages:[{name:'Português',level:'Nativo'},{name:'Inglês',level:'Intermediário'}]
    },
    en: {
      navExp:'Experience',navSkills:'Stack',navProj:'Projects',navForm:'Education',navContact:'Contact',heroHello:'$ hi, I am',heroLead:'QA Analyst working across functional, exploratory, automation and API testing — plus AI applied to quality. I turn requirements into delivery confidence — from test condition to incident report.',heroLoc:'Araçatuba — SP, Brazil',ctaContact:'Get in touch',termStatus:'status: quality on track',skillsKicker:'tech stack',skillsTitle:'Tools & skills',expKicker:'career',expTitle:'Experience',expLead:'From building test conditions to automation, focused on shipping quality products with the team.',valAutoT:'End-to-end automation',valAutoD:'Playwright, Cypress and C# covering UI and APIs, with results visible in Allure reports.',valAiT:'AI applied to quality',valAiD:'LLMs with RAG, agents and MCP integrated into the QA cycle and business processes.',valMetT:'Metrics-driven quality',valMetD:'Quality and life-cycle dashboards pulled from Azure DevOps via WIQL, with AI analysis.',valProcT:'Mature process',valProcD:'TMMi as the international quality reference, with Scrum and Kanban in the team\'s daily work.',projKicker:'cases',projTitle:'Projects & test cases',projLead:'Real projects built along the way — automation, data and AI applied to software quality.',projCta:'View on GitHub',formKicker:'education',formTitle:'Academic background',formLead:'A technology degree, a graduate program in test automation, and continuous learning in software quality.',certTitle:'Courses & certifications',langTitle:'Languages',contactTitle:'Shall we talk about quality?',contactLead:'Open to opportunities and good conversations about testing, automation and software quality. Reach out and let\'s chat. 👋',footerCopy:'Some rights reserved.',
      roles:['QA Analyst','Test Automation','API Testing','AI applied to QA','Exploratory Testing'],
      experience:[
        {year:'2023 —',company:'Technology and healthcare company',role:'QA Analyst',text:'Leading the implementation of the QA process across the development life cycle — from refinement to delivery — bringing automation, metrics, and AI into the team\'s daily work.',highlights:['Built the API-check automation framework with Playwright and C#, with monitoring and visibility through Allure reports.','Helped roll out the TMMi framework with the team, structuring the quality process in line with international references.','Planned and executed test conditions in Azure DevOps with advanced platform knowledge.','Created a desktop dashboard with Electron, React, JavaScript, and Tailwind integrated with Azure DevOps through WIQL for metrics, life cycle, artifacts, estimates, and analysis.','Developed a local LLM with Ollama, FastAPI, and RAG to structure a reusable knowledge base.','Created AI agents with custom tools for artifact analysis and business endpoint queries.','Supported management in developing new team members.'],tags:['Playwright','C#','Allure','Azure DevOps','TMMi','Postman','REST','GraphQL','HotChocolate','LLMs / RAG','MCP','Scrum','Kanban']},
        {year:'2023',company:'Lacrei Saúde',role:'QA Analyst · Volunteer',text:'Quality for a clinical-care platform serving the LGBTQIAPN+ community — test conditions, Gherkin scenarios, Cypress automation and incident reporting.',tags:['Cypress','Gherkin','Postman','Swagger','Kanban','Figma','Notion']},
        {year:'2023',company:'Crowdtest',role:'Tester · Freelance',text:'Exploratory and functional testing across projects in multiple industries on a crowdtesting platform.',tags:['Exploratory Testing','Functional Testing','Web']},
        {year:'2023',company:'uTest',role:'Tester · Freelance',text:'Exploratory, functional, web and mobile testing on international projects, including A.I products.',tags:['A.I','Mobile','Web','Exploratory Testing']},
        {year:'2014 – 21',company:'Graphic Designer',role:'Freelance',text:'Logos, banners, landing pages and social media — a solid UX/UI foundation that now backs a critical QA eye on interfaces.',tags:['Illustrator','Photoshop','HTML','CSS','UX/UI','Figma']}
      ],
      skillGroups:[{name:'Testing',tags:['Exploratory','Functional','Web','Mobile','API']},{name:'Automation',tags:['Playwright','Cypress','C#','JavaScript','Allure','Robot Framework','Gherkin / BDD']},{name:'API & Data',tags:['Postman','REST','GraphQL','HotChocolate','Swagger','SQL Server']},{name:'AI applied to QA',tags:['LLMs / RAG','Ollama','AI agents','MCP','FastAPI','OpenWebUI']},{name:'Process & Tools',tags:['Azure DevOps','WIQL','TMMi','Scrum','Kanban','Notion','Figma']}],
      projects:[
        {kicker:'API Automation',title:'Playwright + C# framework',body:'API-check automation framework built from scratch with Playwright and C#, with monitoring and visibility through Allure reports.',tags:['Playwright','C#','Allure'],url:PROJECT_URLS.playwright,cta:'Explore project'},
        {kicker:'Quality & Data',title:'QA metrics dashboard',body:'Desktop app in Electron + React integrated with Azure DevOps through WIQL: quality metrics, life cycle, risks, and decision support.',tags:['Electron','React','WIQL','MCP'],url:PROJECT_URLS.dashboard,cta:'Explore project'},
        {kicker:'Applied AI',title:'Enterprise LLM with RAG',body:'Local LLM with Ollama and FastAPI over a Markdown RAG knowledge base, specialized queries, and human approval.',tags:['Ollama','RAG','FastAPI','Agents'],url:PROJECT_URLS.llm,cta:'Explore project'},
        {kicker:'E2E Automation',title:'Cypress suite — critical flows',body:'End-to-end scenarios written in Gherkin and automated with Cypress, covering the platform\'s critical flows.',tags:['Cypress','Gherkin','BDD']},
        {kicker:'API Testing',title:'REST & GraphQL collections',body:'Postman collections validating contracts, status codes, security, persistence, and business rules across REST and GraphQL services.',tags:['Postman','GraphQL','Swagger'],url:PROJECT_URLS.apiCollections,cta:'Explore project'},
        {kicker:'QA Documentation',title:'Artifacts & traceability',body:'Test plans and conditions, incident reporting and tracking in Azure DevOps — traceability from requirement to defect.',tags:['Azure DevOps','SQL Server']}
      ],
      degrees:[{type:'Associate degree',course:'Systems Analysis and Development',school:'Uninter'},{type:'Graduate program · In progress',course:'PGATS — Software Test Automation',school:'Faculdade VINCIT'}],
      courses:[{name:'Software Testing Mentorship',hours:'90h+'},{name:'Software Testing & Quality Program',hours:'85h+'},{name:'test.class — Software Testing School',hours:'30h+'},{name:'DTAR — REST API Testing Made Simple',hours:'24h+'},{name:'HTML & CSS for Beginners',hours:'23h'},{name:'UX Design & UI Design',hours:'17h'},{name:'Test Automation with Robot Framework',hours:'7h'},{name:'Automated tests with Cypress — Basic',hours:'4.5h'},{name:'Automated tests with Cypress — Intermediate',hours:'3.5h'},{name:'Automated tests with Cypress — Advanced',hours:'2.5h'}],
      languages:[{name:'Portuguese',level:'Native'},{name:'English',level:'Intermediate'}]
    }
  };

  var state={lang:'pt',theme:'dark'};
  try{var savedTheme=localStorage.getItem('cq-theme');var savedLang=localStorage.getItem('cq-lang');if(savedTheme==='light'||savedTheme==='dark')state.theme=savedTheme;if(savedLang==='pt'||savedLang==='en')state.lang=savedLang;}catch(error){}
  var reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var typedElement,cursorElement,typeTimer,roleIndex=0,characterIndex=0,deleting=false;
  function $(s,c){return(c||document).querySelector(s)}function $$(s,c){return Array.prototype.slice.call((c||document).querySelectorAll(s))}
  function escapeHtml(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
  function tag(cls,v){return '<span class="tag '+cls+'">'+escapeHtml(v)+'</span>'}
  function applyTheme(){document.body.dataset.theme=state.theme}
  function projectLink(project,translation){var url=project.url||GITHUB_URL;var external=/^https?:\/\//i.test(url);var attributes=external?' target="_blank" rel="noopener"':'';var label=project.cta||translation.projCta;return '<a class="btn btn-ghost proj-cta" href="'+escapeHtml(url)+'"'+attributes+'>'+escapeHtml(label)+ARROW_SVG+'</a>'}
  function renderLists(t){
    $('#skills-grid').innerHTML=t.skillGroups.map(function(g){return '<div class="card elev-sm skill-card"><span class="card-kicker">'+escapeHtml(g.name)+'</span><div class="tags-row">'+g.tags.map(function(i){return tag('tag-neutral',i)}).join('')+'</div></div>'}).join('');
    $('#exp-list').innerHTML=t.experience.map(function(j){var h=j.highlights&&j.highlights.length?'<ul class="exp-highlights">'+j.highlights.map(function(i){return '<li>'+escapeHtml(i)+'</li>'}).join('')+'</ul>':'';return '<div class="exp-item"><div class="exp-year">'+escapeHtml(j.year)+'</div><div><div class="exp-head"><h3>'+escapeHtml(j.company)+'</h3><span class="exp-role text-muted">'+escapeHtml(j.role)+'</span></div><p class="exp-text">'+escapeHtml(j.text)+'</p>'+h+'<div class="exp-tags">'+j.tags.map(function(i){return tag('tag-accent',i)}).join('')+'</div></div></div>'}).join('');
    $('#projects-grid').innerHTML=t.projects.map(function(p){return '<div class="card elev-sm project-card" data-tilt><span class="card-kicker">'+escapeHtml(p.kicker)+'</span><span class="card-title">'+escapeHtml(p.title)+'</span><p class="card-body">'+escapeHtml(p.body)+'</p><div class="exp-tags">'+p.tags.map(function(i){return tag('tag-outline',i)}).join('')+'</div>'+projectLink(p,t)+'</div>'}).join('');
    $('#degrees-list').innerHTML=t.degrees.map(function(d){return '<div class="card elev-sm degree-card"><span class="card-kicker">'+escapeHtml(d.type)+'</span><span class="card-title">'+escapeHtml(d.course)+'</span><span class="card-meta">'+escapeHtml(d.school)+'</span></div>'}).join('');
    $('#langs-list').innerHTML=t.languages.map(function(l){return '<div class="lang-row"><span>'+escapeHtml(l.name)+'</span>'+tag('tag-accent',l.level)+'</div>'}).join('');
    $('#courses-list').innerHTML=t.courses.map(function(c){return '<div class="course-row"><span class="course-name">'+escapeHtml(c.name)+'</span><span class="course-hours">'+escapeHtml(c.hours)+'</span></div>'}).join('');bindTilt();
  }
  function applyLanguage(){var t=I18N[state.lang];document.documentElement.lang=state.lang==='pt'?'pt-BR':'en';$$('[data-i18n]').forEach(function(e){var k=e.getAttribute('data-i18n');if(t[k])e.textContent=t[k]});$$('.lang-btn').forEach(function(b){var a=b.dataset.lang===state.lang;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a?'true':'false')});renderLists(t)}
  function typeStep(){var roles=I18N[state.lang].roles;var word=roles[roleIndex%roles.length];var delay;if(!deleting){characterIndex++;if(characterIndex>=word.length){characterIndex=word.length;deleting=true;delay=2100}else delay=80}else{characterIndex--;if(characterIndex<=0){characterIndex=0;deleting=false;roleIndex++;delay=500}else delay=42}typedElement.textContent=word.slice(0,characterIndex);typeTimer=setTimeout(typeStep,delay)}
  function bindTilt(){$$('[data-tilt]').forEach(function(el){el.addEventListener('mousemove',function(ev){var r=el.getBoundingClientRect();var x=((ev.clientY-r.top)/r.height-.5)*-7;var y=((ev.clientX-r.left)/r.width-.5)*7;el.style.transform='perspective(700px) rotateX('+x.toFixed(2)+'deg) rotateY('+y.toFixed(2)+'deg) translateY(-3px)'});el.addEventListener('mouseleave',function(){el.style.transform=''})})}
  function initializeEffects(){var s=$$('[data-stagger]');if(!reducedMotion){s.forEach(function(e){e.style.opacity='0';e.style.transform='translateY(20px)'});requestAnimationFrame(function(){requestAnimationFrame(function(){s.forEach(function(e){var i=parseInt(e.getAttribute('data-stagger'),10)||0;e.style.transition='opacity .7s ease, transform .7s cubic-bezier(.2,.7,.2,1)';e.style.transitionDelay=i*90+'ms';e.style.opacity='1';e.style.transform='none'})})})}var hero=document.getElementById('home');var spot=hero&&hero.querySelector('.hero-spotlight');if(hero&&spot){hero.addEventListener('mousemove',function(ev){var r=hero.getBoundingClientRect();spot.style.background='radial-gradient(560px circle at '+(ev.clientX-r.left)+'px '+(ev.clientY-r.top)+'px, color-mix(in srgb, var(--color-accent) 9%, transparent), transparent 65%)'});hero.addEventListener('mouseleave',function(){spot.style.background='transparent'})}var progress=$('.progress-bar');if(progress){var update=function(){var root=document.documentElement;var max=root.scrollHeight-root.clientHeight;progress.style.width=(max>0?root.scrollTop/max*100:0)+'%'};window.addEventListener('scroll',update,{passive:true});update()}}
  function initializeReveal(){if(!('IntersectionObserver'in window)||reducedMotion)return;var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.style.opacity='1';entry.target.style.transform='none';observer.unobserve(entry.target)}})},{threshold:.1});$$('[data-reveal]').forEach(function(e){if(e.getBoundingClientRect().top>window.innerHeight*.92){e.style.opacity='0';e.style.transform='translateY(26px)';e.style.transition='opacity .7s ease, transform .7s cubic-bezier(.2,.7,.2,1)';observer.observe(e)}})}
  document.addEventListener('DOMContentLoaded',function(){typedElement=$('#typed');cursorElement=$('.typed-cursor');applyTheme();applyLanguage();$('.theme-toggle').addEventListener('click',function(){state.theme=state.theme==='dark'?'light':'dark';applyTheme();try{localStorage.setItem('cq-theme',state.theme)}catch(error){}});$$('.lang-btn').forEach(function(button){button.addEventListener('click',function(){if(button.dataset.lang===state.lang)return;state.lang=button.dataset.lang;try{localStorage.setItem('cq-lang',state.lang)}catch(error){}roleIndex=0;characterIndex=0;deleting=false;applyLanguage();if(reducedMotion)typedElement.textContent=I18N[state.lang].roles[0]})});if(reducedMotion){typedElement.textContent=I18N[state.lang].roles[0];if(cursorElement)cursorElement.style.display='none'}else typeStep();setTimeout(initializeReveal,120);setTimeout(initializeEffects,60)});
})();
